### PR TITLE
Prepend a blank initializer for RubyMine

### PR DESCRIPTION
**Pull request by joeldrapper**

### CODE REVIEW

**Comment by stevegeek** [comment]
What does this help with?

**Comment by joeldrapper** [comment]
Apparently RubyMine warns you that there is no initializer. I pushed this up so the person who reached out to me about it can see if this fixes the warning. Unfortunately because the `Literal::Properties` module is extended, I don’t think we’re going to be able to fix this for literal properties generally.

**Comment by stevegeek** [comment]
Yes as a RubyMine user I see this sort of issue. Want me to play around and see what I might do?

**Comment by joeldrapper** [comment]
Yeah, that would be great! I think the only way is for the entry point to be form `prepend` since that’s the part RubyMine needs to follow.

We could do something like

```ruby
prepend Literal::Properties::ForRubyMine
```

And have that prepend the blank initializer and then extend `Literal::Properties`.

**Pull request closed without merging**
