### PR TITLE
Lift result

### PR DESCRIPTION
**Pull request by joeldrapper**
When working with a result object, it's common to want to handle:

1. the success case,
2. a few specific failure cases, and
3. any remaining failure cases.

I’m proposing a new `lift` API for this:

```ruby
result.lift do |r|
  r.success { |value| "Do something with #{value}." }
  r.failure(SomeSpecificError) { |error| "Do something with a specific error." }
  r.failure { |error| "Do something with any other error that wasn't already handled." }
end
```

`lift` will force you to handle the general `success` and `failure` cases, and you can optionally handle specific failures if you want.

An alternative `lift!` method would only force you to handle the `success` case. You can optionally handle specific failures, but any remaining failures will be raised. In my experience, this is the most common way to deal with unexpected failures. At the end of the day, you usually want to raise them so they are recorded in Sentry or whatever exception tracking system you use.

### CODE REVIEW

**Comment by stevegeek** [comment]
I seem to remember seeing a discussion about this somewhere vs using pattern matching, but cant find it. Got a link or a quick summary of what the difference is here vs using `case/in` ?

**Comment by joeldrapper** [comment]
@stevegeek the problem with pattern matching is it doesn't unwrap the result. If you pattern match so you know the result was successful, you then have to call an unsafe method to get the value out.

**Comment by joeldrapper** [comment]
Updating this to allow you to optionally pass errors to `lift` that *must* be handled. In this sense, it is a little like handling a variant.

```ruby
result.lift(ErrorA, ErrorB) do
  success {}
  failure(ErrorA) {}
  failure(ErrorB) {}
  failure {}
end
```

This is particularly useful when you want to expose it as part of an API.

```ruby
def fetch_something(&)
  Literal::Result(Hash) do
    # api call here
  end.lift(CardError, ConnectionError, &)
end
```

Now, the calling code must handle the specific errors.

```ruby
fetch_something do |res|
  res.success {}
  res.failure(CardError, ConnectionError) {}
  res.failure {}
end
```

**Comment by stevegeek** [comment]
@joeldrapper The 'checked exceptions' idea is interesting!

Was playing with it this morning and noticed a couple of issues I think, opened a PR https://github.com/joeldrapper/literal/pull/43 

On pattern matching, I think it can be used in a very similar manner, apart from `lift` allows for chaining. Wrote some tests above to show what I mean

Btw one thing I came across here is that it might be interesting to consider delegating `deconstruct/_keys` to the value in `Success` (with a respond_to? check otherwise return a empty hash)

**Pull request merged**
